services:
  mongodb:
    image: mongo:8
    container_name: polartwin-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - polartwin-mongo-data:/data/db

volumes:
  polartwin-mongo-data:
